export enum AuditLogActionType {
    LOGIN = 'LOGIN',
    LOGIN_FAILURE = 'LOGIN_FAILURE',
    LOGOUT = 'LOGOUT',
    VIEW_AUDIT_LOG = 'VIEW_AUDIT_LOG',
    SEARCH_AUDIT_LOG = 'SEARCH_AUDIT_LOG',
    VIEW_DASHBOARD = 'VIEW_DASHBOARD',
    SEARCH_DASHBOARD = 'SEARCH_DASHBOARD',
    VIEW_PRODUCT = 'VIEW_PRODUCT',
    SEARCH_PRODUCT = 'SEARCH_PRODUCT',
    CREATE_PRODUCT = 'CREATE_PRODUCT',
    EDIT_PRODUCT = 'EDIT_PRODUCT',
    DELETE_PRODUCT = 'DELETE_PRODUCT',
    VIEW_ORDERS = 'VIEW_ORDERS',
    SEARCH_ORDERS = 'SEARCH_ORDERS',
    DOWNLOAD_ORDER_INVOICE = 'DOWNLOAD_ORDER_INVOICE',
    PRINT_ORDER_INVOICE = 'PRINT_ORDER_INVOICE'
}