export enum AuditLogActionType {
    LOGIN = 'LOGIN',
    LOGIN_FAILURE = 'LOGIN_FAILURE',
    LOGOUT = 'LOGOUT',
    VIEW_AUDIT_LOG = 'VIEW_AUDIT_LOG',
    SEARCH_AUDIT_LOG = 'SEARCH_AUDIT_LOG',
    VIEW_DASHBOARD = 'VIEW_DASHBOARD',
    SEARCH_DASHBOARD = 'SEARCH_DASHBOARD',
    VIEW_PRODUCT = 'VIEW_PRODUCT',
    SEARCH_PRODUCT = 'SEARCH_PRODUCT'
}